---
# Common variables for all environments
app_name: "rea-interactive-bible-BE"
app_user: "interactive-bible"
ansible_user: "interactive-bible"
domain_name: "seisho.emerj.net"
email: "ceo@seisho.emerj.net"
app_directory: "/home/{{ ansible_user }}/{{ app_name }}"
repository_url: "git@github.com:okekolawolesunday009/devops-stage-4.git"

# System settings
nodejs_version: "18"
nginx_sites_enabled: "/etc/nginx/sites-enabled"
nginx_sites_available: "/etc/nginx/sites-available"

# MongoDB settings
mongodb_port: 27017
mongodb_bind_ip: "127.0.0.1"
mongodb_data_dir: "/var/lib/mongodb"
mongodb_log_dir: "/var/log/mongodb"

# Application settings
app_port: 3600

# CloudWatch settings
cloudwatch_log_group: "/aws/ec2/{{ app_name }}"
cloudwatch_region: "us-west-2"

# SSL settings
certbot_email: "{{ email }}"
ssl_cert_path: "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"
ssl_key_path: "/etc/letsencrypt/live/{{ domain_name }}/privkey.pem"

# Application logs
app_log_dir: "/var/log/{{ app_name }}"