---
# Common handlers

- name: reload ufw
  service:
    name: ufw
    state: reloaded

- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted

- name: restart mongod
  service:
    name: mongod
    state: restarted

- name: restart nginx
  service:
    name: nginx
    state: restarted
